buildspecs:
  kernel_version:
    type: script
    executor: '(cori|perlmutter).local.bash'
    description: check and match kernel version
    run: uname -r 
    tags: [daily, system]
    executors:
      cori.local.bash:            
        status:
          regex:
            stream: stdout
            exp: "^5.3.18-24.107-default$"
      perlmutter.local.bash:            
        status:
          regex:
            stream: stdout
            exp: "^5.14.21-150400.24.11_12.0.57-cray_shasta_c$"

maintainers:
  - "shahzebsiddiqui"
