
buildspecs:
  kernel_version:
    type: script
    executor: cori.local.bash
    description: check and match kernel version
    run: uname -r 
    tags: [daily, system]
    status:
      regex:
        stream: stdout
        exp: "^4.12.14-150.75-default$"

maintainers:
  - "shahzebsiddiqui"
