version: "1.0"
buildspecs:
  petsc_fortran_example:
    type: script
    executor: cori.slurm.haswell_debug
    description: Run petsc fortran example for e4s/21.05 stack
    tags: [e4s]
    sbatch: [-n 4, -t 10]
    run: |
      module load e4s/21.05
      cp $(spack location -i petsc)/share/petsc/examples/src/snes/tutorials/makefile .
      cp $(spack location -i petsc)/share/petsc/examples/src/snes/tutorials/ex5f.F90 .
      cp $(spack location -i petsc)/share/petsc/examples/src/snes/tutorials/ex5f.h .
      make PETSC_DIR=$(spack location -i petsc) ex5f
      srun -n 4  ./ex5f -da_processors_x 2 -da_processors_y 2 -snes_monitor_short -ksp_gmres_cgs_refinement_type refine_always
