version: "1.0"
buildspecs:  
  petsc_checks_e4s_21.05:
    type: script
    executor: cori.slurm.haswell_debug
    description: petsc tests for e4s/21.05 deployment
    tags: [e4s]
    sbatch: [-n 4, -t 10] 
    run: |
      module load e4s/21.05
      cp $(spack location -i petsc)/share/petsc/examples/src/ksp/ksp/tutorials/ex50.c .
      cp $(spack location -i petsc)/share/petsc/examples/src/ksp/ksp/tutorials/makefile .
      make PETSC_DIR=$(spack location -i petsc) ex50
      srun -n 4 ex50 -da_grid_x 4 -da_grid_y 4 -ksp_monitor

      rm makefile
      
      cp $(spack location -i petsc)/share/petsc/examples/src/snes/tutorials/ex19.c .
      cp $(spack location -i petsc)/share/petsc/examples//src/snes/tutorials/makefile .
      make PETSC_DIR=$(spack location -i petsc) ex19
      # petsc with superlu_dist test
      srun -n 4 ex19 -da_grid_x 20 -da_grid_y 20 -pc_type lu -pc_factor_mat_solver_type superlu_dist
      # petsc with hypre test  
      srun -n 4 ex19 -da_refine 3 -snes_monitor_short -pc_type hypre  

