buildspecs:
  petsc_fortran_example_22.02:
    type: script
    executor: cori.slurm.haswell_debug
    description: Run petsc fortran example for e4s/22.02 stack
    tags: [e4s]
    sbatch: [-n 4, -t 10]
    run: |
      module load e4s/22.02
      export PETSC_LOC=$(spack location -i petsc@3.16.4%gcc@11.2.0)
      cp ${PETSC_LOC}/share/petsc/examples/src/snes/tutorials/makefile .
      cp ${PETSC_LOC}/share/petsc/examples/src/snes/tutorials/ex5f.F90 .
      cp ${PETSC_LOC}/share/petsc/examples/src/snes/tutorials/ex5f.h .
      make PETSC_DIR=${PETSC_LOC} ex5f
      srun -n 4  ./ex5f -da_processors_x 2 -da_processors_y 2 -snes_monitor_short -ksp_gmres_cgs_refinement_type refine_always
