version: "1.0"
buildspecs:
  spack_test_hdf5_e4s_21.02:
    type: spack
    executor: cori.local.sh
    description: Test HDF5 from e4s/21.02 using spack test
    tags: e4s
    pre_cmds: module load e4s/21.02
    spack:
      root: /global/common/software/spackecp/e4s-21.02/spack/
      verify_spack: false
      test:
        run:
          specs: ['hdf5@1.10.7%gcc', 'hdf5@1.10.7%intel']
        results:
          option: '-l'
          specs: ['hdf5@1.10.7%gcc', 'hdf5@1.10.7%intel']
maintainers:
  - "@shahzebsiddiqui"
