version: "1.0"
buildspecs: 
  spack_test_qthreads_e4s_21.02:
    type: spack
    executor: cori.local.sh
    description: qthreads E4S 21.02 test via spack test
    tags: e4s
    pre_cmds: module load e4s/21.02
    spack:
      root: /global/common/software/spackecp/e4s-21.02/spack/
      verify_spack: false
      test: 
        run:
          specs: ['qthreads@1.16']
        results:
          option: '-l'
          specs: ['qthreads@1.16']
maintainers:
  - "@shahzebsiddiqui"
