version: "1.0"
buildspecs:
  hello_world_openmp:
    type: compiler
    executor: cori.slurm.knl_debug
    source: src/hello.c
    description: Hello World OpenMP scaling example with processor count
    tags: [openmp]
    compilers:
      name: ["^PrgEnv-intel/6.0.5"]
      default:
        intel:
          env:
            OMP_NUM_THREADS: "$BUILDTEST_NUMPROCS"
          cflags: -qopenmp
          sbatch: ["-t 10"]
