version: "1.0"
buildspecs:
  bupc_hello:
    type: compiler
    executor: cori.slurm.haswell_debug
    description: "bupc hello world example in C"
    source: src/bupc-hello.c
    tags: ["compile"]
    compilers:
      name: ["builtin_gcc"]
      default:
        gcc:
          cc: upcc
          cflags: -g --network=aries
          run: upcrun -N 2 -n 8 $_EXEC
          sbatch: ["-t 10", "-n 8", "-N 2"]
      config:
        builtin_gcc:
          module:
            load: [bupc/2020.4.0]
