
buildspecs:
  bupc_hello:
    type: compiler
    executor: cori.slurm.knl_debug
    description: "bupc hello world example in C"
    source: src/bupc-hello.c
    tags: ["compile"]
    compilers:
      name: ["builtin_gcc"]
      default:
        gcc:
          cc: upcc
          cflags: -g --network=aries
          run: upcrun -N 1 -n 4 $_EXEC
          sbatch: ["-t 10", "-n 4", "-N 1"]
      config:
        builtin_gcc:
          module:
            load: [bupc]
