buildspecs:
  spack_test_hypre_e4s_22.05:
    type: spack
    executor: '(perlmutter|muller).local.sh'
    description: "Test hypre build with for e4s/22.05 stack on Perlmutter via spack test"
    tags: e4s
    pre_cmds: |
      module load e4s/22.05
      spack env activate -V gcc
      spack load --first hypre
    spack:
      root: /global/common/software/spackecp/perlmutter/e4s-22.05/default/spack/
      verify_spack: false
      test:
        run:
          specs: ['hypre']
        results:
          option: '-l'
          specs: ['hypre']
