buildspecs:
  spack_test_tasmanian_e4s_22.05:
    type: spack
    executor: '(perlmutter|muller).local.sh'
    description: "Test tasmanian build with for e4s/22.05 stack on Perlmutter via spack test"
    summary: | 
      This test fails see https://github.com/E4S-Project/e4s/issues/111
    tags: e4s
    pre_cmds: |
      module load e4s/22.05
      spack env activate -V gcc
      spack load --first tasmanian
    spack:
      root: /global/common/software/spackecp/perlmutter/e4s-22.05/default/spack/
      verify_spack: false
      test:
        run:
          specs: ['tasmanian']
        results:
          option: '-l'
          specs: ['tasmanian']
    status:
      state: FAIL


