variables:
  BUILDTEST_REPO: "https://github.com/buildtesters/buildtest"
  BUILDTEST_REPO_BRANCH: "devel"
  
stages:
  - build

validate_tests:
  stage: build
  tags:
    - cori06
  
  script:
    - pwd
    - module load python
    - git clone {BUILDTEST_REPO} -b {BUILDTEST_REPO_BRANCH}
    - pipenv shell
    - python setup.py install
    - buildtest --help
    - buildtest repo list
    - buildtest repo add https://github.com/buildtesters/buildtest-cori
    - buildtest buildspec find
  
