variables:
  SCHEDULER_PARAMETERS: "-N 1 -M escori -t 06:00:00 -q compile"
  
.setup-buildtest: &setup-buildtest
  - module load python
  - conda create -p $CI_PROJECT_DIR/.conda python=3.8 -y
  - source activate buildtest
  - git clone -b devel https://github.com/buildtesters/buildtest    
  - cd buildtest 
  - . setup.sh
  - buildtest --help
  - rm -rf $HOME/.buildtest
  - mkdir -p $HOME/.buildtest
  
.cleanup-buildtest: &cleanup-buildtest
  - conda env remove -p $CI_PROJECT_DIR/.conda  -y
  
stages:
  - build
  - test
validate_tests:
  stage: build
  tags: [cori]
  before_script:
    - *setup-buildtest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "push"'
      when: manual
  script:
    - whoami    
    - cd $CI_PROJECT_DIR/
    - cp $CI_PROJECT_DIR/config.yml $HOME/.buildtest/config.yml
    - buildtest config validate    
    - buildtest buildspec find --rebuild --root $CI_PROJECT_DIR/buildspecs
    - mkdir -p $CI_PROJECT_DIR/.artifacts
    - cp $HOME/.buildtest/buildspecs/{cache.json,error.txt} $CI_PROJECT_DIR/.artifacts
    - source deactivate 
  
  after_script:
    - *cleanup-buildtest
  
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.artifacts       
    expire_in: 2 week

scheduled_system_check:
  stage: test
  only:
    refs:
      - schedules
    variables:
      - $DAILYCHECK == "True"
  tags: [cori]
  before_script:
    - *setup-buildtest
  script:
    - whoami && ls -l 
    - git log --oneline -1
    - echo $CI_PROJECT_DIR   
    - cd $CI_PROJECT_DIR
    - cp $CI_PROJECT_DIR/config.yml $HOME/.buildtest/config.yml
    - buildtest config validate
    - buildtest buildspec find --rebuild --root $CI_PROJECT_DIR/buildspecs
    - buildtest build --tags daily -ft daily -r $BUILDTEST_ROOT/report.json
    - buildtest report --filter state=FAIL -r $BUILDTEST_ROOT/report.json
    - mkdir -p $CI_PROJECT_DIR/.artifacts
    - cp $BUILDTEST_ROOT/{buildtest.log,report.json} $CI_PROJECT_DIR/.artifacts
    - buildtest cdash upload daily_check -r $BUILDTEST_ROOT/report.json
    - source deactivate 
  after_script:
    - *cleanup-buildtest
  
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.artifacts      
    expire_in: 2 week

apps:
  stage: test
  tags: [cori]
  only: 
    refs: 
      - schedules
    variables:
      - $APP == "True"

  before_script:
  - *setup-buildtest
  script:
    - cd $CI_PROJECT_DIR
    - cp $CI_PROJECT_DIR/config.yml $HOME/.buildtest/config.yml
    - buildtest config validate
    - buildtest build --tags compile --filter-tags compile -r $BUILDTEST_ROOT/report.json
    - buildtest report --filter state=FAIL -r $BUILDTEST_ROOT/report.json
    - mkdir -p $CI_PROJECT_DIR/.artifacts
    - cp $BUILDTEST_ROOT/{buildtest.log,report.json} $CI_PROJECT_DIR/.artifacts
    - buildtest cdash upload apps -r $BUILDTEST_ROOT/report.json
    - source deactivate 
  after_script:
    - *cleanup-buildtest
    
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.artifacts

benchmark:
  stage: test
  tags: [cori]
  only:
    refs:
      - schedules
    variables:
      - $BENCHMARK == "True"

  before_script:
  - *setup-buildtest
  script:
    - cd $CI_PROJECT_DIR
    - buildtest -c $CI_PROJET_DIR/config.yml config validate
    - buildtest -c $CI_PROJECT_DIR/config.yml build --tags benchmark --filter-tags benchmark -r $BUILDTEST_ROOT/report.json
    - buildtest report --filter state=FAIL -r $BUILDTEST_ROOT/report.json
    - mkdir -p $CI_PROJECT_DIR/.artifacts
    - cp $BUILDTEST_ROOT/{buildtest.log,report.json} $CI_PROJECT_DIR/.artifacts
    - buildtest cdash upload benchmark -r $BUILDTEST_ROOT/report.json
    - source deactivate
  after_script:
    - *cleanup-buildtest

  artifacts:
    paths:
      - $CI_PROJECT_DIR/.artifacts

e4s_tests:
  stage: test
  only:
    refs:
      - schedules
    variables:
      - $E4S == "True"
  tags: [cori]
  before_script:
    - *setup-buildtest
  script:
    - whoami && ls -l 
    - git log --oneline -1
    - echo $CI_PROJECT_DIR   
    - cd $CI_PROJECT_DIR
    - cp $CI_PROJECT_DIR/config.yml $HOME/.buildtest/config.yml
    - buildtest config validate
    - buildtest buildspec find --rebuild --root $CI_PROJECT_DIR/buildspecs
    - buildtest build --tags e4s -r $BUILDTEST_ROOT/report.json
    - buildtest report --filter state=FAIL -r $BUILDTEST_ROOT/report.json
    - mkdir -p $CI_PROJECT_DIR/.artifacts
    - cp $BUILDTEST_ROOT/{buildtest.log,report.json} $CI_PROJECT_DIR/.artifacts
    - buildtest cdash upload e4s -r $BUILDTEST_ROOT/report.json
    - source deactivate 
  after_script:
    - *cleanup-buildtest
    
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.artifacts
    expire_in: 2 week
    
