stages:
  - build

validate_tests:
  stage: build
  tags:
    - cori06
  
  script:
    - pwd
    - module load python
    - git clone -b devel https://github.com/buildtesters/buildtest
    - pipenv shell
    - python setup.py install
    - buildtest --help
    - buildtest repo list
    - buildtest repo add https://github.com/buildtesters/buildtest-cori
    - buildtest buildspec find
  
