executors:
  local:
    bash:
      description: submit jobs on local machine using bash shell
      shell: bash

    sh:
      description: submit jobs on local machine using sh shell
      shell: sh

    python:
      description: submit jobs on local machine using python shell
      shell: python
  slurm:
    debug:
      description: interactive haswell qos
      launcher: sbatch
      options: ["-q debug"]

config:
  editor: vi
  paths:
    prefix: $HOME/cache/
