executors:
  local:
    bash:
      description: submit jobs on local machine using bash shell
      shell: bash

    sh:
      description: submit jobs on local machine using sh shell
      shell: sh

    python:
      description: submit jobs on local machine using python shell
      shell: python
  slurm:
    debug:
      description: debug qos
      launcher: sbatch
      options: ["-q debug"]
      pollinterval: 20
    regular:
      description: regular qos
      launcher: sbatch
      options: ["-q regular"]
      pollinterval: 20
    bigmem:
      description: interactive qos
        launcher: sbatch
        options: ["-q bigmem -M escori"]
        pollinterval: 20
config:
  editor: vi
  paths:
    prefix: $HOME/cache/
