buildspecs:
  hpctoolkit_cuda:
    executor: '(perlmutter|muller).slurm.regular'
    type: script
    description: "HPCToolkit vector add CUDA test with PC sampling"
    tags: ["e4s"]
    sbatch: ["-A m3503 -C gpu -N 1 -G 1 -t 00:05:00"]
    run: |
      module load e4s/22.05
      module load PrgEnv-nvidia
      spack env activate -V e4s
      spack load hpctoolkit+cuda

      cd cuda_vecadd
      make clean
      make NVCC_OPTS="-g -arch=sm_80"

      OUT=hpctoolkit-vecadd-pc
      N=1048576

      rm -rf ${OUT}.m ${OUT}.d
      srun --ntasks-per-node=1 dcgmi profile --pause
      srun -n 1 -c 1 -G 1 \
        hpcrun -e gpu=nvidia,pc -o ${OUT}.m \
        ./a.out $N
      srun --ntasks-per-node=1 dcgmi profile --resume

      srun -n 1 -c 64 -G 0 \
        hpcstruct --gpucfg yes ${OUT}.m

      srun -n 1 -c 64 -G 0 \
        hpcprof -o ${OUT}.d ${OUT}.m

    status:
      regex:
        stream: stdout
        exp: "OK"
      exists:
        - hpctoolkit-vecadd-pc.d

maintainers:
  - wyphan
  - blue42u
