buildspecs:
  hpctoolkit_cuda:
    executor: '(perlmutter|muller).slurm.regular'
    type: script
    description: "HPCToolkit vector add CUDA test with PC sampling"
    tags: ["e4s"]
    sbatch: ["-A m3503", "-C gpu", "-N 1", "-G 1", "-t 00:05:00"]
    run: |
      module load e4s/22.05 || exit $?
      module load PrgEnv-nvidia || exit $?
      spack env activate -V cuda || exit $?
      spack load hpctoolkit+cuda || exit $?

      rm -f cuda_vecadd
      nvcc -o cuda_vecadd -g -arch=sm_80 cuda_vecadd.cu || exit $?

      out=hpctoolkit-vecadd-pc
      n=1048576

      srun --ntasks-per-node=1 dcgmi profile --pause || exit $?
      rm -rf $out.m
      srun -n 1 -c 1 -G 1 hpcrun -e gpu=nvidia,pc -o $out.m ./cuda_vecadd $n || exit $?
      srun --ntasks-per-node=1 dcgmi profile --resume || exit $?

      # Expect 1 combined profile
      if [ "$(ls -1 $out.m/ | grep '\.hpcrun$' | wc -l)" -ne 1 ]; then
        echo "FAIL: Wrong number of profiles recorded!"
        exit 1
      fi

      # Expect at least 100 GPU samples total
      if [ "$(grep 'accelerator samples:' $out.m/*.log | grep --only-matching 'recorded: [[:digit:]]\+' | awk '{print $2}')" -lt 100 ]; then
        echo "FAIL: Not enough samples recorded!"
        exit 3
      fi

      srun -n 1 -c 64 -G 0 hpcstruct --gpucfg yes $out.m || exit $?

      # Expect a gpubin struct file
      if ! test -e $out.m/structs/*.gpubin-gpucfg-yes.hpcstruct; then
        echo "FAIL: missing struct file"
        exit 4
      fi
      
      rm -rf $out.d
      srun -n 1 -c 64 -G 0 hpcprof -o $out.d $out.m || exit $?

      # Expect the old XML format database files
      # TODO: update to new binary format for HPCToolkit >= 2022.10
      for fn in experiment.dtd experiment.xml; do
        if ! test -e $out.d/$fn; then
          echo "FAIL: Missing database file $fn"
          exit 5
        fi
      done

    status:
      returncode: 0

maintainers:
  - wyphan
  - blue42u
