buildspecs:
  hpctoolkit_cuda:
    executor: '(perlmutter|muller).slurm.regular'
    type: script
    description: "HPCToolkit vector add CUDA test"
    tags: ["e4s"]
    sbatch: ["-A m3503", "-C gpu", "-N 1", "-G 1", "-t 00:05:00"]
    run: |
      module load e4s/22.05 || exit $?
      module load PrgEnv-nvidia || exit $?
      spack env activate -V cuda || exit $?
      spack load hpctoolkit+cuda || exit $?

      rm -f cuda_vecadd
      nvcc -o cuda_vecadd -g -arch=sm_80 cuda_vecadd.cu || exit $?

      out=hpctoolkit-vecadd
      n=1048576

      rm -rf $out.m
      srun -n 1 -c 1 -G 1 hpcrun -e REALTIME -e gpu=nvidia -t -o $out.m ./cuda_vecadd $n || exit $?
      srun -n 1 -c 64 -G 0 hpcstruct $out.m || exit $?      
      rm -rf $out.d
      srun -n 1 -c 64 -G 0 hpcprof -o $out.d $out.m || exit $?

    metrics:
      accelerator_samples:
        type: int
        file_regex:
          file: "hpctoolkit-vecadd.m/*.log"
          exp: '.processed: [[:digit:]]\+'
          item: 1

    status:
      mode: "all"
      returncode: 0
      assert_ge:
      - name: accelerator_samples
        ref: 100
      file_count:
      - dir: "hpctoolkit-vecadd.m"
        ext: ".hpcrun"
        depth: 1
        count: 2
      - dir: "hpctoolkit-vecadd.m"
        ext: ".hpctrace"
        depth: 1
        count: 2
      - dir: "hpctoolkit-vecadd.m/structs"
        filepattern: '\.gpubin-gpucfg-no\.hpcstruct$'
        depth: 1
        count: 1
      exists:
      - "hpctoolkit-vecadd.d/experiment.dtd"
      - "hpctoolkit-vecadd.d/experiment.xml"

maintainers:
  - wyphan
  - blue42u
