buildspecs:
  hpctoolkit_cuda:
    executor: '(perlmutter|muller).slurm.regular'
    type: script
    description: "HPCToolkit vector add CUDA test"
    tags: ["e4s"]
    sbatch: ["-A m3503", "-C gpu", "-N 1", "-G 1", "-t 00:05:00"]
    run: |
      module load e4s/22.05 || exit $?
      module load PrgEnv-nvidia || exit $?
      spack env activate -V e4s || exit $?
      spack load hpctoolkit+cuda || exit $?

      rm -f cuda_vecadd
      nvcc -o cuda_vecadd -g -arch=sm_80 cuda_vecadd.cu || exit $?

      out=hpctoolkit-vecadd
      n=1048576

      rm -rf $out.m
      srun -n 1 -c 1 -G 1 hpcrun -e REALTIME -e gpu=nvidia -o $out.m ./cuda_vecadd $n || exit $?

      # Expect 2 profiles, one for the CPU thread and one for the GPU
      if [ "$(ls -1 $out.m/ | grep '\.hpcrun$' | wc -l)" -ne 2 ]; then
        echo "FAIL: Wrong number of profiles recorded!"
        exit 1
      fi
      # Expect at least 10 samples total
      if [ "$(grep --only-matching '^SUMMARY: samples: [[:digit:]]\+' $out.m/*.log | awk '{print $3}')" -lt 10 ]; then
        echo "FAIL: Not enough samples recorded!"
        exit 1
      fi

      srun -n 1 -c 64 -G 0 hpcstruct $out.m || exit $?

      rm -rf $out.d
      srun -n 1 -c 64 -G 0 hpcprof -o $out.d $out.m || exit $?

      # Expect the usual database files (no trace.db)
      # TODO: experiment.xml was replaced by meta.db in HPCToolkit 2022.10
      for fn in experiment.xml profile.db cct.db; do
        if ! test -e $out.d/$fn; then
          echo "FAIL: Missing database file $fn"
          exit 1
        fi
      done

    status:
      returncode: 0

maintainers:
  - '@wyphan'
  - '@blue42u'
