buildspecs:
  spack_test_gasnet_e4s_21.11:
    type: spack
    executor: '(perlmutter|muller).local.sh'
    description: "Test gasnet build with for e4s/21.11 stack on Perlmutter via spack test"
    tags: e4s
    pre_cmds: |
      module load e4s/21.11
      spack env activate -V e4s
      spack load --first gasnet
    spack:
      root: /global/common/software/spackecp/perlmutter/e4s-21.11/default/spack/
      verify_spack: false
      test:
        run:
          specs: ['gasnet']
        results:
          option: '-l'
          specs: ['gasnet']


