buildspecs:
  spack_test_hdf5_e4s_21.11:
    type: spack
    executor: '(perlmutter|muller).local.sh'
    description: "Test hdf5@1.12.1 for e4s/21.11 stack for Perlmutter via spack test"
    tags: e4s
    pre_cmds: |
      module load e4s/21.11
      spack env activate -V e4s
      spack load --first hdf5@1.12.1
    spack:
      root: /global/common/software/spackecp/perlmutter/e4s-21.11/default/spack/
      verify_spack: false
      test:
        run:
          specs: ['hdf5@1.12.1']
        results:
          option: '-l'
          specs: ['hdf5@1.12.1']

  spack_test_hdf5_e4s_22.05:
    type: spack
    executor: '(perlmutter|muller).local.sh'
    description: "Test hdf5 for e4s/22.05 stack for Perlmutter via spack test"
    tags: e4s
    pre_cmds: |
      module load e4s/22.05
      spack env activate -V gcc
      spack load --first hdf5
    spack:
      root: /global/common/software/spackecp/perlmutter/e4s-22.05/default/spack/
      verify_spack: false
      test:
        run:
          specs: ['hdf5']
        results:
          option: '-l'
          specs: ['hdf5']
