buildspecs:
  spack_test_heffte_e4s_21.11:
    type: spack
    executor: '(perlmutter|muller).local.sh'
    description: "Test heffte build with for e4s/22.05 stack on Perlmutter via spack test"
    summary: | 
      This test fails see https://github.com/E4S-Project/e4s/issues/112
    tags: e4s
    pre_cmds: |
      module load e4s/22.05
      spack env activate -V gcc
      spack load --first heffte
    spack:
      root: /global/common/software/spackecp/perlmutter/e4s-22.05/default/spack/
      verify_spack: false
      test:
        run:
          specs: ['heffte']
        results:
          option: '-l'
          specs: ['heffte']
    status:
      state: FAIL


