buildspecs:
  spack_test_py-warpx-22.05:
    type: spack
    executor: 'perlmutter.local.sh'
    description: "Test py-warpx build with for e4s/22.05 stack on Perlmutter via spack test"
    summary: |
      This test will run 'spack test run' on py-warpx. For more details on the issue see 
      https://github.com/buildtesters/buildtest-nersc/issues/158
    tags: e4s
    pre_cmds: |
      module load e4s/22.05
      # need to swap to cpu module otherwise you get an error with GTL Library
      ml cpu
      spack env activate -V gcc
      spack load --first py-warpx
    spack:
      root: /global/common/software/spackecp/perlmutter/e4s-21.11/default/spack/
      verify_spack: false
      test:
        run:
          specs: ['py-warpx']
        results:
          option: '-l'
          specs: ['py-warpx']


