buildspecs:
  spack_test_superlu-dist_e4s_22.05:
    type: spack
    executor: '(perlmutter|muller).local.sh'
    description: "Test superlu-dist build for e4s/22.05 stack on Perlmutter"
    tags: e4s
    pre_cmds: |
      module load e4s/22.05
      spack env activate -V gcc
      spack load --first superlu-dist
    spack:
      root: /global/common/software/spackecp/perlmutter/e4s-22.05/default/spack/
      verify_spack: false
      test:
        run:
          specs: ['superlu-dist' ]
        results:
          option: '-l'
          specs: ['superlu-dist']
