version: "1.0"
buildspecs:
  spack_test_upcxx_e4s_21.11:
    type: spack
    executor: perlmutter.local.sh
    description: "Test upcxx build with nvhpc for e4s/21.11 stack on Perlmutter via spack test"
    tags: e4s
    pre_cmds: |
      module load e4s/21.11-tcl
      module load PrgEnv-nvidia
    spack:
      root: /global/common/software/spackecp/perlmutter/e4s-21.11/spack/
      verify_spack: false
      test:
        run:
          specs: ['upcxx %nvhpc']
        results:
          option: '-l'
          specs: ['upcxx %nvhpc']

