buildspecs:
  spack_test_kokkos_e4s_21.05:
    type: spack
    executor: cori.local.sh
    description: Test kokkos@3.4.00 for e4s/21.05 using spack test
    tags: e4s
    pre_cmds: |
      module swap intel intel/19.1.3.304
      module load e4s/21.05
      module load cmake/3.20.2-intel-19.1.3.304
    spack:
      root: /global/common/software/spackecp/e4s-21.05/spack/
      verify_spack: false
      test:
        run:
          specs: ['kokkos@3.4.00 +openmp', 'kokkos@3.4.00 -openmp']
        results:
          specs: ['kokkos@3.4.00 +openmp', 'kokkos@3.4.00 -openmp']
    status:
      state: "FAIL"
  spack_test_kokkos_e4s_22.02:
    type: spack
    executor: cori.local.bash
    description: Test kokkos for e4s/22.02 using spack test
    tags: e4s
    pre_cmds: |
      module load e4s/22.02
    spack:
      root: /global/common/software/spackecp/cori/e4s-22.02/spack/
      verify_spack: false
      test:
        run:
          specs: ['kokkos']
        results:
          specs: ['kokkos']
maintainers:
  - "shahzebsiddiqui"
