buildspecs:
  spack_test_petsc_e4s_22.02:
    type: spack
    executor: cori.local.bash
    description: Test petsc from e4s/22.02 using spack test
    tags: e4s
    pre_cmds: module load e4s/22.02
    status:
     state: FAIL
    spack:
      root: /global/common/software/spackecp/cori/e4s-22.02/spack/
      verify_spack: false
      test:
        run:
          specs: ['petsc']
        results:
          option: '-l'
          specs: ['petsc']
maintainers:
  - "shahzebsiddiqui"
