version: "1.0"
buildspecs:
  upc_hello:
    type: compiler
    executor: cori.slurm.knl_debug
    description: Hello world in upc
    source: src/hello_upcxx.cpp
    tags: [compile]
    compilers:
      name: [builtin_gcc]
      default:
        gcc:
          sbatch: ["-t 01:00", "-N 1"]
          cxx: upcxx
          cxxflags: "-g --network=aries"
          run: upcxx-run -N 1 -n 8 $_EXEC
      config:
        builtin_gcc:
          module:
            load: [upcxx/2020.3.0]
