
buildspecs:
  bupc_pi:
    type: compiler
    executor: cori.slurm.haswell_debug
    description: PI calculation using bupc
    source: src/pi.c
    tags: [compile]
    compilers:
      name: ["^(upcxx\/2020.10.0)$"]
      default:
        upcxx:
          sbatch: ["-t 10", "-N 1"]
          cc: upcc
          run: upcrun -n 4 ./$_EXEC
