executors:

  defaults:
    pollinterval: 10
    launcher: sbatch

  local:
    bash:
      description: submit jobs on local machine using bash shell
      shell: bash

    sh:
      description: submit jobs on local machine using sh shell
      shell: sh

    python:
      description: submit jobs on local machine using python shell
      shell: python

  slurm:
    debug:
      description: jobs for debug qos
      qos: debug
      cluster: cori

    shared:
      description: jobs for shared qos
      qos: shared

    bigmem:
      description: bigmem jobs
      cluster: escori
      qos: bigmem

    xfer:
      description: xfer qos jobs
      qos: xfer
    
    gpu:
      description: submit jobs to GPU partition
      options: ["-C gpu"]
      cluster: escori

config:
  editor: vi
  paths:
    prefix: $HOME/cache/
    buildspec_root:
      - $HOME/buildtest-cori
