load_default_buildspecs: False
buildspec_roots:
- $HOME/buildtest-cori
moduletool: environment-modules
executors:
  defaults:
    pollinterval: 10
    launcher: sbatch
    max_pend_time: 90
    account: nstaff
  local:
    bash:
      description: submit jobs on local machine using bash shell
      shell: bash
    sh:
      description: submit jobs on local machine using sh shell
      shell: sh
    csh:
      description: submit jobs on local machine using csh shell
      shell: csh
    python:
      description: submit jobs on local machine using python shell
      shell: python
    e4s:
      description: E4S testsuite locally
      shell: bash
      before_script: |
        source /global/common/software/spackecp/e4s-20.10/spack/share/spack/setup-env.sh
        cd $SCRATCH/testsuite
        source setup.sh

  slurm:
    debug:
      description: jobs for debug qos
      qos: debug
      cluster: cori
      max_pend_time: 500
    shared:
      description: jobs for shared qos
      qos: shared
      max_pend_time: 10
    bigmem:
      description: bigmem jobs
      cluster: escori
      qos: bigmem
      max_pend_time: 300
    xfer:
      description: xfer qos jobs
      qos: xfer
      cluster: escori
    gpu:
      description: submit jobs to GPU partition
      options:
      - -C gpu
      cluster: escori
      max_pend_time: 300
    premium:
      description: submit jobs to premium queue
      qos: premium
    e4s:
      description: E4S runner
      cluster: cori
      max_pend_time: 20000
      options:
      - -q regular
      - -C knl
      - -t 10
      - -n 4
      before_script: |
        source /global/common/software/spackecp/e4s-20.10/spack/share/spack/setup-env.sh
        cd $SCRATCH/testsuite
        source setup.sh

compilers:
  find:
    gcc:
    - gcc
    - PrgEnv-gnu
    cray:
    - PrgEnv-cray
    intel:
    - intel
    - PrgEnv-intel
    pgi:
    - pgi
  compiler:
    gcc:
      builtin:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        fc: /usr/bin/gfortran
      gcc@6.1.0:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - gcc/6.1.0
      gcc@7.3.0:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - gcc/7.3.0
      gcc@8.1.0:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - gcc/8.1.0
      gcc@8.2.0:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - gcc/8.2.0
      gcc@8.3.0:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - gcc/8.3.0
      gcc@9.3.0:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - gcc/9.3.0
      gcc@10.1.0:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - gcc/10.1.0
      gcc@6.3.0:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - gcc/6.3.0
      gcc@8.1.1-openacc-gcc-8-branch-20190215:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - gcc/8.1.1-openacc-gcc-8-branch-20190215
      PrgEnv-gnu@6.0.5:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - PrgEnv-gnu/6.0.5
      PrgEnv-gnu@6.0.7:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - PrgEnv-gnu/6.0.7
      PrgEnv-gnu@6.0.9:
        cc: gcc
        cxx: g++
        fc: gfortran
        modules:
        - PrgEnv-gnu/6.0.9
    cray:
      PrgEnv-cray@6.0.5:
        cc: cc
        cxx: CC
        fc: ftn
        modules:
        - PrgEnv-cray/6.0.5
      PrgEnv-cray@6.0.7:
        cc: cc
        cxx: CC
        fc: ftn
        modules:
        - PrgEnv-cray/6.0.7
      PrgEnv-cray@6.0.9:
        cc: cc
        cxx: CC
        fc: ftn
        modules:
        - PrgEnv-cray/6.0.9
    intel:
      intel@19.0.3.199:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/19.0.3.199
      intel@19.1.2.254:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/19.1.2.254
      intel@16.0.3.210:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/16.0.3.210
      intel@17.0.1.132:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/17.0.1.132
      intel@17.0.2.174:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/17.0.2.174
      intel@19.0.0.117:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/19.0.0.117
      intel@19.0.8.324:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/19.0.8.324
      intel@19.1.0.166:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/19.1.0.166
      intel@19.1.1.217:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/19.1.1.217
      intel@19.1.2.275:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/19.1.2.275
      intel@19.1.3.304:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - intel/19.1.3.304
      PrgEnv-intel@6.0.5:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - PrgEnv-intel/6.0.5
      PrgEnv-intel@6.0.7:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - PrgEnv-intel/6.0.7
      PrgEnv-intel@6.0.9:
        cc: icc
        cxx: icpc
        fc: ifort
        modules:
        - PrgEnv-intel/6.0.9
    pgi:
      pgi@18.10:
        cc: pgcc
        cxx: pgc++
        fc: pgfortran
        modules:
        - pgi/18.10
      pgi@19.1:
        cc: pgcc
        cxx: pgc++
        fc: pgfortran
        modules:
        - pgi/19.1
      pgi@19.3:
        cc: pgcc
        cxx: pgc++
        fc: pgfortran
        modules:
        - pgi/19.3
      pgi@19.4:
        cc: pgcc
        cxx: pgc++
        fc: pgfortran
        modules:
        - pgi/19.4
      pgi@19.5:
        cc: pgcc
        cxx: pgc++
        fc: pgfortran
        modules:
        - pgi/19.5
      pgi@19.7:
        cc: pgcc
        cxx: pgc++
        fc: pgfortran
        modules:
        - pgi/19.7
      pgi@19.9:
        cc: pgcc
        cxx: pgc++
        fc: pgfortran
        modules:
        - pgi/19.9
      pgi@19.10:
        cc: pgcc
        cxx: pgc++
        fc: pgfortran
        modules:
        - pgi/19.10
      pgi@20.1:
        cc: pgcc
        cxx: pgc++
        fc: pgfortran
        modules:
        - pgi/20.1
      pgi@20.4:
        cc: pgcc
        cxx: pgc++
        fc: pgfortran
        modules:
        - pgi/20.4
