editor: vi
buildspec_roots:
  - $HOME/buildtest-cori
executors:

  defaults:
    pollinterval: 10
    launcher: sbatch
    max_pend_time: 90
    account: nstaff

  local:
    bash:
      description: submit jobs on local machine using bash shell
      shell: bash

    sh:
      description: submit jobs on local machine using sh shell
      shell: sh

    csh:
      description: submit jobs on local machine using csh shell
      shell: csh

    python:
      description: submit jobs on local machine using python shell
      shell: python

    e4s:
      description: "E4S testsuite locally"
      shell: bash
      before_script: |
        source /global/common/software/spackecp/luke-wyatt-testing/spack/share/spack/setup-env.sh
        cd $SCRATCH/testsuite
        source setup.sh

  slurm:
    debug:
      description: jobs for debug qos
      qos: debug
      cluster: cori
      max_pend_time: 500

    shared:
      description: jobs for shared qos
      qos: shared
      max_pend_time: 10

    bigmem:
      description: bigmem jobs
      cluster: escori
      qos: bigmem
      max_pend_time: 300

    xfer:
      description: xfer qos jobs
      qos: xfer
      cluster: escori

    gpu:
      description: submit jobs to GPU partition
      options: ["-C gpu"]
      cluster: escori
      max_pend_time: 300

    premium:
      description: submit jobs to premium queue
      qos: premium

    e4s:
      description: "E4S runner"
      cluster: cori
      max_pend_time: 20000
      options: 
        - "-q regular"
        - "-C knl"
        - "-t 10"
        - "-n 4"
      before_script: |

        source /global/common/software/spackecp/luke-wyatt-testing/spack/share/spack/setup-env.sh
        cd $SCRATCH/testsuite
        source setup.sh
