version: "0.1"
buildspecs:
  amrex_single_vortex:
    type: script
    executor: cori.local.bash
    description: "AmrLevel SingleVortex Build and Run"
    tags: ["daily"]
    compilers:
      name: ["^(intel@19.1.3.304)$"]
      default:
        pre_build: |
          module load e4s/21.05
          #module load impi                 # Fixes missing MPI error
          spack load amrex                 # Load installed AMMReX Library
          spack load cmake@3.20.3          # Load spack latest version of cmake
          export AMR_DIR=$(spack location -i amrex) # Store root directory of AMReX install
        run: |
          mkdir build
          cd build
          cmake .. \
           -DAMReX_DIR=${AMR_DIR}/lib/cmake/AMReX \
           -DCMAKE_CXX_COMPLIER=$(which icpc) \
           -DCMAKE_C_COMPILER=$(which icc) \
           -DAMReX_SPACEDIM=3
          cmake --build . -j4
          srun -n 4 ./SingleVortex ../inputs max_step=1

      config:
        intel/19.1.3.304:
          module:
            swap: [intel, intel/19.1.3.304]
            load: [impi]
