version: "1.0"
buildspecs:
  amrex_single_vortex:
    executor: cori.slurm.haswell_debug
    type: script
    description: "AmrLevel SingleVortex Build and Run"
    tags: ["daily"]
    sbatch:
      - "-N 1"
      - "-t 00:10:00"
    run: |
      echo "my script it running"
      module load e4s/21.05
      echo "Load intel compiler"
      module load intel/19.1.3.304

      module load impi
      spack load amrex
      spack load cmake@3.20.2

      export AMR_DIR=$(spack location -i amrex)

      spack find amrex

      cd test/Exec
      mkdir build
      cd build

      cmake .. \
      -DAMReX_DIR=${AMR_DIR}/lib/cmake/AMReX \
      -DCMAKE_CXX_COMPILER=$(which icpc) \
      -DCMAKE_C_COMPILER=$(which icc) \
      -DAMReX_SPACEDIM=3

      cmake --build . -j4
      srun -n 4 ./SingleVortex ../inputs max_step=1

    status:
      regex:
        stream: stdout
        exp: "finalized"
maintainers:
  - epalmer
