buildspecs:
  amrex_single_vortex:
    executor: cori.slurm.haswell_debug
    type: script
    description: "AMReX SpackSmokeTest Build and Run"
    # As of AMReX release 22.04, the CMakeLists.txt file is updated and this
    # workaround to enable Fortran for this test should not be needed. 
    tags: ["e4s"]
    sbatch:
      - "-N 1"
      - "-t 00:10:00"
    run: |
      module load e4s/22.02
      spack load amrex
      spack load --first cmake@3.22.2%intel

      # Store AMReX install location
      export AMR_DIR=$(spack location -i amrex)

      # Copy test files to writable directory
      mkdir amrex_test_tmp
      cd amrex_test_tmp

      # Copy test files from AMReX Spack directory to temp directory
      cp -r ${AMR_DIR}/.spack/test/Tests/. .
      cd SpackSmokeTest
      cp ../../smoketest_workaround/CMakeLists.txt .
 
      mkdir build
      cd build

      cmake .. \
      -DAMReX_FORTRAN=ON \
      -DAMReX_FORTRAN_INTERFACES=ON \
      -DAMReX_DIR=${AMR_DIR}/lib/cmake/AMReX \
      -DAMReX_SPACEDIM=3

      cmake --build . -j4

      srun -n 4 ./install_test ../../Amr/Advection_AmrCore/Exec/inputs-ci

    status:
      regex:
        stream: stdout
        exp: "finalized"
maintainers:
  - epalmer
