version: "1.0"
buildspecs:
  create_burst_buffer:
    type: script
    executor: cori.slurm.knl_debug
    description: Create a burst buffer
    tags: [jobs, cray]
    sbatch: ["-N 1", "-t 5", "-n 1"]
    BB: 
      - create_persistent name=databuffer capacity=10GB access_mode=striped type=scratch
    DW: 
      - persistentdw name=databuffer
    run: |
      cd $DW_PERSISTENT_STRIPED_databuffer
      pwd
      dd if=/dev/urandom of=random.txt bs=1G count=5 iflag=fullblock
      ls -lh $DW_PERSISTENT_STRIPED_databuffer/
