version: "1.0"
buildspecs:
  delete_burst_buffer:
    type: script
    executor: cori.slurm.haswell_debug
    sbatch: ["-C knl", "-N 1", "-t 5", "n 1"]
    description: Delete a burst buffer
    tags: [jobs, cray]
    BB: 
      - destroy_persistent name=databuffer 
    run: |
      cd $DW_PERSISTENT_STRIPED_databuffer/
      pwd
      ls -l 
