version: "1.0"
buildspecs:
  cplusplus_hello:
    executor: cori.local.bash
    type: compiler
    description: hello world program in C++ compiled with gnu compiler
    tags: [compile]
    source: src/hello.cpp
    compilers:
      name: [ '^(gcc)']
