version: "1.0"
buildspecs: 
  spack_test_raja_e4s_21.02:
    type: spack
    executor: cori.local.sh
    description: "Test raja@0.13.0 e4s/21.02 test via spack test"
    tags: e4s
    pre_cmds: module load e4s/21.02
    spack:
      root: /global/common/software/spackecp/e4s-21.02/spack/
      verify_spack: false
      test: 
        run:
          specs: ['raja@0.13.0']
        results:
          option: '-l'
          specs: ['raja@0.13.0']

  spack_test_raja_e4s_21.05:
    type: spack
    executor: cori.local.sh
    description: "Test raja@0.13.0 for e4s/21.05 test via spack test"
    tags: e4s
    pre_cmds: module load e4s/21.05
    spack:
      root: /global/common/software/spackecp/e4s-21.05/spack/
      verify_spack: false
      test:
        run:
          specs: ['raja@0.13.0%intel']
        results:
          option: '-l'
          specs: ['raja@0.13.0%intel']

maintainers:
  - "shahzebsiddiqui"
