buildspecs:
  module_version:
    type: script
    executor: '(perlmutter|cori).local.bash'
    description: check module version of startup module
    tags: [daily, system, module]
    run: module --version
    executors:  
      cori.local.bash:
        status:
          regex:
            stream: stderr
            exp: "^(VERSION=3.2.11.4)"
      perlmutter.local.bash:
        status:
          regex:
            stream: stderr
            exp: 'Modules based on Lua: Version 8\.7\.15'

maintainers:
  - "shahzebsiddiqui"
