
buildspecs:
  auto_swap_same_modules:
    type: script
    executor: perlmutter.local.bash
    description: Check if Lmod will autoswap same modules
    tags: [module]
    run: |
      ml gcc/10.3.0
      ml gcc/9.3.0
