buildspecs:
  myquota:
    type: script
    executor: '(cori|perlmutter).local.bash'
    description: Run myquota --check which returns any quota violation. 
    tags: ["daily", "system", "tool"]
    run: myquota --check

  myquota_numbers:
    type: script
    executor: '(cori|perlmutter).local.bash'
    description: Run myquota -H which shows quota in human readable format
    tags: ["daily", "system", "tool"]
    run: myquota -H

  myquota_scratch:
    type: script
    executor: '(cori|perlmutter).local.bash'
    description: Check quota for $SCRATCH
    tags: ["daily", "system", "tool"]
    run: myquota $SCRATCH

maintainers:
  - "shahzebsiddiqui"


