version: "1.0"
buildspecs:
  git_version:
    type: script
    executor: cori.local.bash
    tags: [tool, daily]
    description: "Check version of /usr/bin/git"
    run: /usr/bin/git --version
    status:
      regex:
        stream: stdout
        exp: 'git version (2.26.1)'
maintainers:
  - "shahzebsiddiqui"
