version: "1.0"
buildspecs:
  mkl_gnu_threaded:
    type: script
    executor: cori.slurm.haswell_debug
    sbatch: [ "-N 1", "-t 15"]
    description: dgemm performance using mkl gnu threaded - user ticket INC0167504
    tags: [benchmark, ticket]
    run: |
      module swap PrgEnv-intel PrgEnv-gnu
      make -f Makefile.mkl_gnu_threaded
      export OMP_PLACES=threads
      export OMP_PROC_BIND=spread
      OMP_NUM_THREADS=1 srun -c 64 --cpu_bind=cores ./run
      OMP_NUM_THREADS=4 srun -c 64 --cpu_bind=cores ./run
      OMP_NUM_THREADS=16 srun -c 64 --cpu_bind=cores ./run
      make clean  


